// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPNnWsM1jQuIPRF8gWE5Xu6oTnbPG5qBQ',
    appId: '1:696018676494:web:4469c6adbb356258cc055f',
    messagingSenderId: '696018676494',
    projectId: 'wasteguard-bcecb',
    authDomain: 'wasteguard-bcecb.firebaseapp.com',
    storageBucket: 'wasteguard-bcecb.appspot.com',
    measurementId: 'G-KTZK5C506H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0kMDJXIhFe7GlQF_I0Lh02qpqpIgR5-o',
    appId: '1:696018676494:android:48547ed9b11e85e6cc055f',
    messagingSenderId: '696018676494',
    projectId: 'wasteguard-bcecb',
    storageBucket: 'wasteguard-bcecb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3dkP7_2kBWiNM4vnA3kLkHrm4Uo23J5o',
    appId: '1:696018676494:ios:57277f8d6d1afb85cc055f',
    messagingSenderId: '696018676494',
    projectId: 'wasteguard-bcecb',
    storageBucket: 'wasteguard-bcecb.appspot.com',
    iosBundleId: 'com.example.wasteguard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3dkP7_2kBWiNM4vnA3kLkHrm4Uo23J5o',
    appId: '1:696018676494:ios:44f604818d723ca3cc055f',
    messagingSenderId: '696018676494',
    projectId: 'wasteguard-bcecb',
    storageBucket: 'wasteguard-bcecb.appspot.com',
    iosBundleId: 'com.example.wasteguard.RunnerTests',
  );
}
